apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: frontend
        api: external        
    spec:
      containers:
      - image: flavio0choa/udacity-frontend:latest
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "100m"                
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: "frontend"
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8100

