apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: flavio0choa/reverseproxy
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "100m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always
apiVersion: v1
kind: Service
metadata:
  name: "reverseproxy"
spec:
  selector:
    app: reverseproxy
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080



